# Generated by Django 4.2.11 on 2024-07-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_fireincident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FireIncident',
        ),
    ]
